import Head from "next/head";
import Message from "../components/message";
import { useEffect, useState } from "react";
import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

export default function Home() {

    //Create a state with all the posts
    const [allPosts, setAllPosts] = useState([]);

    const getPosts = async () => {
      const collectionRef = collection(db, "posts");
      const q = query(collectionRef, orderBy("timestamp", "desc"));
      const unsubscribe = onSnapshot(q, (snapshot) => {
        setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
      });
      return unsubscribe;
    };
  
    useEffect(() => {
      getPosts();
    }, []);

  return (
    <div>
      <Head>
        <title>Creative Thoughts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h1>See what other people are saying</h1>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button className="commentbtn">
                {post.comments?.length > 0 ? post.comments?.length : 0} comments
              </button>
            </Link>
          </Message>
        ))}
      </div>

      <footer>
        <a
          href="https://github.com/hafizmp/creative-thoughts"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span> &copy; Creative Thoughts 2022 </span>
        </a>
      </footer>
    </div>
  )
}
